### ISSUE TITLE
How to upload video in HtmlToolbarPreset.Media annotation?

### ISSUE THREAD

**Issue by ramkrish3020** [cofoundry-cms/Cofoundry.Samples.SimpleSite#6]
Hi,
![image](https://user-images.githubusercontent.com/20699474/62677620-9a050d00-b9cc-11e9-8305-1d50cff12bca.png)
![image](https://user-images.githubusercontent.com/20699474/62677635-a8ebbf80-b9cc-11e9-87a1-5b8f5337c4d4.png)

  I tried to upload my video using Html Annotation HtmlToolbarPreset.Media using but I saw only past embedded tag and insert source that type option.
My requirement upload the video option for example image upload. can you please help me on this

**Comment by HeyJoel** [comment]
There's no specific functionality for uploading video files in Cofoundry, typically we'd expect you to use a 3rd party hosting service that was optimized to host and stream large video files.

You can however use documents to upload video files, but they wouldn't be integrated into the html editor

**Comment by ramkrish3020** [comment]
> There's no specific functionality for uploading video files in Cofoundry, typically we'd expect you to use a 3rd party hosting service that was optimized to host and stream large video files.
> 
> You can however use documents to upload video files, but they wouldn't be integrated into the html editor

I tried upload video file  extention .mov use documents.I got error can you see my error below 

![image](https://user-images.githubusercontent.com/20699474/63166048-d5e24700-c04a-11e9-940c-8ee55d81b477.png)








![image](https://user-images.githubusercontent.com/20699474/63166075-f3171580-c04a-11e9-8d1a-2e8d1a61cdde.png)

**Comment by ramkrish3020** [comment]
Hi @HeyJoel any idea of that error in above screen I tried upload videos file in document annotation I got this error.

Thanks
 Ram

**Comment by HeyJoel** [comment]
If you inspect the response to the post request (e.g. in chrome/FF tools - network tab) you'll probably see that the error is actually:

> 404.13: The request filtering module is configured to deny a request that exceeds the request content length.

I expect you're trying to upload a file that is too big for your current security settings. If this is the case then this is handled outside of Cofoundry and will depend on your hosting setup. There's some suggestions [on this stackoverflow post](https://stackoverflow.com/questions/46510836/http-error-404-13-asp-net-core-2-0?rq=1) if that is the error you are having.

**Comment by ramkrish3020** [comment]
thanks @HeyJoel  it's working.
